import { CommonAsyncLoadingTypes } from ".";
export type NavigationType = Partial<any & CommonAsyncLoadingTypes>;
export type SEO = Partial<any & CommonAsyncLoadingTypes>;
export type Blog = Partial<any & CommonAsyncLoadingTypes>;
export type Blogs = Partial<any & CommonAsyncLoadingTypes>;
export type CustomPage = Partial<any & CommonAsyncLoadingTypes>;
export type FAQData = Partial<any & CommonAsyncLoadingTypes>;
export type Tags = Partial<any & CommonAsyncLoadingTypes>;
export type LegalData = Partial<any & CommonAsyncLoadingTypes>;
export type ScreenSaver = Partial<any & CommonAsyncLoadingTypes>;
export type SupportInformation = Partial<any & CommonAsyncLoadingTypes>;
export type Announcement = Partial<any & CommonAsyncLoadingTypes>;
export type LandingPage = Partial<any & CommonAsyncLoadingTypes>;
export type DataLoaders = Partial<any & CommonAsyncLoadingTypes>;
export type FAQS = Partial<any & CommonAsyncLoadingTypes>;
export type FaqCategory = Partial<any & CommonAsyncLoadingTypes>;
export type FaqCategories = Partial<any & CommonAsyncLoadingTypes>;
export type ContentSlice = {
    navigation: NavigationType;
    seo: SEO;
    faqs: FAQS;
    blog: Blog;
    faqCategories: FaqCategories;
    faqCategory: FaqCategory;
    blogs: Blogs;
    custom_page: CustomPage;
    faq_data: FAQData;
    tags: Tags;
    legal_data: LegalData;
    screen_saver: ScreenSaver;
    support_information: SupportInformation;
    announcement: Announcement;
    landing_page: LandingPage;
    data_loaders: DataLoaders;
};
